bumblebee:
  # Telegram bot token
  token:
  # Command mapping
  commands:
    StartCommand: /start /help
    StatusCommand: /status
    YoutubeSearchCommand: /v /y
    BingPictureSearchCommand: /g /p /i
  # Webhook settings
  webhook:
    enabled: false # false - long polling will be used, true - webhooks
    url:

# Commands
## Youtube search
youtube:
  api:
    projectName:
    key:

# Bing Search API
bing:
  api:
    accountKey:
