# Telegram bot token
bumblebee:
  token:
  commands:
    StartCommand: /start /help
    StatusCommand: /status
    YoutubeSearchCommand: /v /video
    GooglePictureSearchCommand: /p /g /pic
  webhook:
    enabled: false # false - long polling will be used, true - webhooks
    url:

# Commands
## Youtube search
youtube:
  api:
    projectName:
    key:
